### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by mynkow** [joshuadeanhall/AspNet.Identity.Cassandra#1]
Hey,

is this working?

**Comment by joshuadeanhall** [comment]
mynkow currently it is not working.

**Comment by joshuadeanhall** [comment]
mynkow,

The cassandra driver was recently updated and my plan is to use that instead as I ran into some issues with the older driver that made things more difficult.

**Comment by joshuadeanhall** [comment]
The initial release is now complete I will fix bugs and make improvements as needed.
